CHUNK_BUSTER:
  LIMIT_PER_PLAYER: 2
  DELAY: 5
  IGNORED_BLOCKS:
  - "BEDROCK"

ITEM:
  NAME: "&6&lChunk Buster"
  LORE:
  - "&7Place it down to start busting chunk."
  MATERIAL: "REDSTONE_TORCH_ON"

ALREADY_RUNNING_MAX_BUSTERS: "&7You are already running maximum amount of chunk busters!"
ALREADY_BUSTING_THIS_CHUNK: "&7Chunk buster is already &crunning &7in this chunk!"
CHUNK_ALREADY_BUSTED: "&7This chunk has already been busted!"
BUSTER_STARTING: "&7Chunk buster will start removing blocks in &c<seconds> &7seconds!"

BUSTER_COMMAND:
  NO_PERMISSION: "&cSorry! &7You do not have permission for this command!"
  INVALID_NUMBER: "&7Please use a valid &cnumber&7!"
  PLAYER_NOT_ONLINE: "&7Player &c<player> &7is currently not online!"
  RELOADED: "&aReloaded all Chunk buster's config files."
  GIVE_MESSAGE: "&7You gave &c<amount> &7chunk buster items to &c<player>&7."
  USAGE:
  - "&c&m    &8&m                                                      &c&m    "
  - " &7&l* &c/&7chunkbuster give &c<&7player&c> <&7amount&c>"
  - " &7&l* &c/&7chunkbuster reload"
  - "&c&m    &8&m                                                      &c&m    "